language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"
install: "if [ `python -c 'import sys; print sys.version_info < (2, 7)'` = True ]; then pip install unittest2; fi"
script: ./run-tests.sh
